version: "3"

services:

  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - "./config:/etc/selenoid:ro"
      - "//./pipe/docker_engine://./pipe/docker_engine"

  test-runner:
    build: .
    container_name: test-runner
    depends_on:
      - selenoid
    volumes:
      - .:/app
